USE PRACTICAADO
GO
CREATE PROCEDURE GETEMPRESAS
AS
	SELECT EMPRESA FROM CLIENTES
GO
ALTER PROCEDURE GETCLIENTE(@N NVARCHAR(40))
AS
	DECLARE @COD NVARCHAR(40)
	SELECT @COD = CODIGOCLIENTE FROM CLIENTES
	WHERE EMPRESA = @N
	SELECT * FROM CLIENTES
	WHERE CODIGOCLIENTE = @COD
GO
ALTER PROCEDURE GETPEDIDOS(@COD NVARCHAR(40))
AS
	SELECT CodigoPedido FROM PEDIDOS
	WHERE CODIGOCLIENTE = @COD
GO
ALTER PROCEDURE GETPEDIDO(@N NVARCHAR(40),@COD NVARCHAR(40))
AS
	DECLARE @C NVARCHAR(40)
	SELECT @C = CODIGOCLIENTE FROM CLIENTES
	WHERE EMPRESA = @N
	SELECT * FROM PEDIDOS
	WHERE CODIGOCLIENTE = @C
	AND CodigoPedido = @COD
GO
ALTER PROCEDURE MODIFICARCLIENTE(@N NVARCHAR(40),@EM NVARCHAR(40),@CA NVARCHAR(40),@CO NVARCHAR(40),@CI NVARCHAR(40),@TE NVARCHAR(40))
AS

	DECLARE @C NVARCHAR(40)
	SELECT @C = CODIGOCLIENTE FROM CLIENTES
	WHERE EMPRESA = @N
	UPDATE CLIENTES SET EMPRESA = @EM,CARGO = @CA,
	CONTACTO = @CO,CIUDAD = @CI,TELEFONO = @TE
	WHERE CODIGOCLIENTE = @C

GO
ALTER PROCEDURE ELIMINARPEDIDO(@EM NVARCHAR(40),@P NVARCHAR(40))
AS
	DECLARE @C NVARCHAR(40)
	SELECT @C = CODIGOCLIENTE FROM CLIENTES
	WHERE EMPRESA = @EM
	DELETE FROM PEDIDOS
	WHERE CODIGOCLIENTE = @C
	AND CODIGOPEDIDO = @P
GO
ALTER PROCEDURE MODIFICARPEDIDO(@EM NVARCHAR(40),@P NVARCHAR(40),@FEC NVARCHAR(40),@FO NVARCHAR(40),@IM NVARCHAR(40))
AS
	DECLARE @C NVARCHAR(40)
	SELECT @C = CODIGOCLIENTE FROM CLIENTES
	WHERE EMPRESA = @EM
	INSERT INTO PEDIDOS VALUES(@P,@C,@FEC,@FO,@IM)
GO