//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TcapContext : DbContext
    {
        public TcapContext()
            : base("name=TcapContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<PARTICPANTS> PARTICPANTS { get; set; }
        public virtual DbSet<PARTIES> PARTIES { get; set; }
        public virtual DbSet<PLAYERS> PLAYERS { get; set; }
        public virtual DbSet<PUBS> PUBS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<STATUSES> STATUSES { get; set; }
        public virtual DbSet<TICKETS> TICKETS { get; set; }
        public virtual DbSet<TOKENS> TOKENS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
