//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKENS
    {
        public int ID_TOKEN { get; set; }
        public int ID_USER { get; set; }
        public string VALUE_TOKEN { get; set; }
        public System.DateTime START_TOKEN { get; set; }
        public System.DateTime END_TOKEN { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
