//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMVC.ServicioCatastro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Callejero de la sede electrónica del catastro.Soap", Namespace="http://tempuri.org/OVCServWeb/OVCCallejero", ConfigurationName="ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap")]
    public interface CallejerodelasedeelectrónicadelcatastroSoap {
        
        // CODEGEN: Generating message contract since the operation Consulta_DNPRC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPRC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.Consulta_DNPRCResponse Consulta_DNPRC(AzureMVC.ServicioCatastro.Consulta_DNPRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPRC", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPRCResponse> Consulta_DNPRCAsync(AzureMVC.ServicioCatastro.Consulta_DNPRCRequest request);
        
        // CODEGEN: Generating message contract since the operation ObtenerProvincias is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaProvincia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.ConsultaProvincia1 ObtenerProvincias(AzureMVC.ServicioCatastro.ConsultaProvincia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaProvincia", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaProvincia1> ObtenerProvinciasAsync(AzureMVC.ServicioCatastro.ConsultaProvincia request);
        
        // CODEGEN: Generating message contract since the operation ObtenerMunicipios is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaMunicipio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.ConsultaMunicipio1 ObtenerMunicipios(AzureMVC.ServicioCatastro.ConsultaMunicipio request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaMunicipio", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaMunicipio1> ObtenerMunicipiosAsync(AzureMVC.ServicioCatastro.ConsultaMunicipio request);
        
        // CODEGEN: Generating message contract since the operation ObtenerCallejero is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaVia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.ConsultaVia1 ObtenerCallejero(AzureMVC.ServicioCatastro.ConsultaVia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaVia", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaVia1> ObtenerCallejeroAsync(AzureMVC.ServicioCatastro.ConsultaVia request);
        
        // CODEGEN: Generating message contract since the operation ObtenerNumerero is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaNumero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.ConsultaNumero1 ObtenerNumerero(AzureMVC.ServicioCatastro.ConsultaNumero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/ConsultaNumero", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaNumero1> ObtenerNumereroAsync(AzureMVC.ServicioCatastro.ConsultaNumero request);
        
        // CODEGEN: Generating message contract since the operation Consulta_DNPLOC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPLOC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse Consulta_DNPLOC(AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPLOC", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse> Consulta_DNPLOCAsync(AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest request);
        
        // CODEGEN: Generating message contract since the operation Consulta_DNPPP is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPPP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AzureMVC.ServicioCatastro.Consulta_DNPPPResponse Consulta_DNPPP(AzureMVC.ServicioCatastro.Consulta_DNPPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVCServWeb/OVCCallejero/Consulta_DNPPP", ReplyAction="*")]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPPPResponse> Consulta_DNPPPAsync(AzureMVC.ServicioCatastro.Consulta_DNPPPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPRCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=2)]
        public string RefCat;
        
        public Consulta_DNPRCRequest() {
        }
        
        public Consulta_DNPRCRequest(string Provincia, string Municipio, string RefCat) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
            this.RefCat = RefCat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPRCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Consulta_DNP;
        
        public Consulta_DNPRCResponse() {
        }
        
        public Consulta_DNPRCResponse(System.Xml.XmlNode Consulta_DNP) {
            this.Consulta_DNP = Consulta_DNP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaProvincia {
        
        public ConsultaProvincia() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaProvincia1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Provincias;
        
        public ConsultaProvincia1() {
        }
        
        public ConsultaProvincia1(System.Xml.XmlNode Provincias) {
            this.Provincias = Provincias;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaMunicipio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        public ConsultaMunicipio() {
        }
        
        public ConsultaMunicipio(string Provincia, string Municipio) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaMunicipio1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Municipios;
        
        public ConsultaMunicipio1() {
        }
        
        public ConsultaMunicipio1(System.Xml.XmlNode Municipios) {
            this.Municipios = Municipios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaVia {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=2)]
        public string TipoVia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=3)]
        public string NombreVia;
        
        public ConsultaVia() {
        }
        
        public ConsultaVia(string Provincia, string Municipio, string TipoVia, string NombreVia) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
            this.TipoVia = TipoVia;
            this.NombreVia = NombreVia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaVia1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Callejero;
        
        public ConsultaVia1() {
        }
        
        public ConsultaVia1(System.Xml.XmlNode Callejero) {
            this.Callejero = Callejero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNumero {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=2)]
        public string TipoVia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=3)]
        public string NomVia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=4)]
        public string Numero;
        
        public ConsultaNumero() {
        }
        
        public ConsultaNumero(string Provincia, string Municipio, string TipoVia, string NomVia, string Numero) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
            this.TipoVia = TipoVia;
            this.NomVia = NomVia;
            this.Numero = Numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNumero1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Callejero;
        
        public ConsultaNumero1() {
        }
        
        public ConsultaNumero1(System.Xml.XmlNode Callejero) {
            this.Callejero = Callejero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPLOCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=2)]
        public string Sigla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=3)]
        public string Calle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=4)]
        public string Numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=5)]
        public string Bloque;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=6)]
        public string Escalera;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=7)]
        public string Planta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=8)]
        public string Puerta;
        
        public Consulta_DNPLOCRequest() {
        }
        
        public Consulta_DNPLOCRequest(string Provincia, string Municipio, string Sigla, string Calle, string Numero, string Bloque, string Escalera, string Planta, string Puerta) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
            this.Sigla = Sigla;
            this.Calle = Calle;
            this.Numero = Numero;
            this.Bloque = Bloque;
            this.Escalera = Escalera;
            this.Planta = Planta;
            this.Puerta = Puerta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPLOCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Consulta_DNP;
        
        public Consulta_DNPLOCResponse() {
        }
        
        public Consulta_DNPLOCResponse(System.Xml.XmlNode Consulta_DNP) {
            this.Consulta_DNP = Consulta_DNP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPPPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public string Provincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=1)]
        public string Municipio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=2)]
        public string Poligono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=3)]
        public string Parcela;
        
        public Consulta_DNPPPRequest() {
        }
        
        public Consulta_DNPPPRequest(string Provincia, string Municipio, string Poligono, string Parcela) {
            this.Provincia = Provincia;
            this.Municipio = Municipio;
            this.Poligono = Poligono;
            this.Parcela = Parcela;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_DNPPPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.catastro.meh.es/", Order=0)]
        public System.Xml.XmlNode Consulta_DNPPP;
        
        public Consulta_DNPPPResponse() {
        }
        
        public Consulta_DNPPPResponse(System.Xml.XmlNode Consulta_DNPPP) {
            this.Consulta_DNPPP = Consulta_DNPPP;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallejerodelasedeelectrónicadelcatastroSoapChannel : AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallejerodelasedeelectrónicadelcatastroSoapClient : System.ServiceModel.ClientBase<AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap>, AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap {
        
        public CallejerodelasedeelectrónicadelcatastroSoapClient() {
        }
        
        public CallejerodelasedeelectrónicadelcatastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallejerodelasedeelectrónicadelcatastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallejerodelasedeelectrónicadelcatastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallejerodelasedeelectrónicadelcatastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.Consulta_DNPRCResponse AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPRC(AzureMVC.ServicioCatastro.Consulta_DNPRCRequest request) {
            return base.Channel.Consulta_DNPRC(request);
        }
        
        public System.Xml.XmlNode Consulta_DNPRC(string Provincia, string Municipio, string RefCat) {
            AzureMVC.ServicioCatastro.Consulta_DNPRCRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPRCRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.RefCat = RefCat;
            AzureMVC.ServicioCatastro.Consulta_DNPRCResponse retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPRC(inValue);
            return retVal.Consulta_DNP;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPRCResponse> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPRCAsync(AzureMVC.ServicioCatastro.Consulta_DNPRCRequest request) {
            return base.Channel.Consulta_DNPRCAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPRCResponse> Consulta_DNPRCAsync(string Provincia, string Municipio, string RefCat) {
            AzureMVC.ServicioCatastro.Consulta_DNPRCRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPRCRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.RefCat = RefCat;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPRCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.ConsultaProvincia1 AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerProvincias(AzureMVC.ServicioCatastro.ConsultaProvincia request) {
            return base.Channel.ObtenerProvincias(request);
        }
        
        public System.Xml.XmlNode ObtenerProvincias() {
            AzureMVC.ServicioCatastro.ConsultaProvincia inValue = new AzureMVC.ServicioCatastro.ConsultaProvincia();
            AzureMVC.ServicioCatastro.ConsultaProvincia1 retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerProvincias(inValue);
            return retVal.Provincias;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaProvincia1> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerProvinciasAsync(AzureMVC.ServicioCatastro.ConsultaProvincia request) {
            return base.Channel.ObtenerProvinciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaProvincia1> ObtenerProvinciasAsync() {
            AzureMVC.ServicioCatastro.ConsultaProvincia inValue = new AzureMVC.ServicioCatastro.ConsultaProvincia();
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerProvinciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.ConsultaMunicipio1 AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerMunicipios(AzureMVC.ServicioCatastro.ConsultaMunicipio request) {
            return base.Channel.ObtenerMunicipios(request);
        }
        
        public System.Xml.XmlNode ObtenerMunicipios(string Provincia, string Municipio) {
            AzureMVC.ServicioCatastro.ConsultaMunicipio inValue = new AzureMVC.ServicioCatastro.ConsultaMunicipio();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            AzureMVC.ServicioCatastro.ConsultaMunicipio1 retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerMunicipios(inValue);
            return retVal.Municipios;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaMunicipio1> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerMunicipiosAsync(AzureMVC.ServicioCatastro.ConsultaMunicipio request) {
            return base.Channel.ObtenerMunicipiosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaMunicipio1> ObtenerMunicipiosAsync(string Provincia, string Municipio) {
            AzureMVC.ServicioCatastro.ConsultaMunicipio inValue = new AzureMVC.ServicioCatastro.ConsultaMunicipio();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerMunicipiosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.ConsultaVia1 AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerCallejero(AzureMVC.ServicioCatastro.ConsultaVia request) {
            return base.Channel.ObtenerCallejero(request);
        }
        
        public System.Xml.XmlNode ObtenerCallejero(string Provincia, string Municipio, string TipoVia, string NombreVia) {
            AzureMVC.ServicioCatastro.ConsultaVia inValue = new AzureMVC.ServicioCatastro.ConsultaVia();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.TipoVia = TipoVia;
            inValue.NombreVia = NombreVia;
            AzureMVC.ServicioCatastro.ConsultaVia1 retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerCallejero(inValue);
            return retVal.Callejero;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaVia1> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerCallejeroAsync(AzureMVC.ServicioCatastro.ConsultaVia request) {
            return base.Channel.ObtenerCallejeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaVia1> ObtenerCallejeroAsync(string Provincia, string Municipio, string TipoVia, string NombreVia) {
            AzureMVC.ServicioCatastro.ConsultaVia inValue = new AzureMVC.ServicioCatastro.ConsultaVia();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.TipoVia = TipoVia;
            inValue.NombreVia = NombreVia;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerCallejeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.ConsultaNumero1 AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerNumerero(AzureMVC.ServicioCatastro.ConsultaNumero request) {
            return base.Channel.ObtenerNumerero(request);
        }
        
        public System.Xml.XmlNode ObtenerNumerero(string Provincia, string Municipio, string TipoVia, string NomVia, string Numero) {
            AzureMVC.ServicioCatastro.ConsultaNumero inValue = new AzureMVC.ServicioCatastro.ConsultaNumero();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.TipoVia = TipoVia;
            inValue.NomVia = NomVia;
            inValue.Numero = Numero;
            AzureMVC.ServicioCatastro.ConsultaNumero1 retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerNumerero(inValue);
            return retVal.Callejero;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaNumero1> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.ObtenerNumereroAsync(AzureMVC.ServicioCatastro.ConsultaNumero request) {
            return base.Channel.ObtenerNumereroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.ConsultaNumero1> ObtenerNumereroAsync(string Provincia, string Municipio, string TipoVia, string NomVia, string Numero) {
            AzureMVC.ServicioCatastro.ConsultaNumero inValue = new AzureMVC.ServicioCatastro.ConsultaNumero();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.TipoVia = TipoVia;
            inValue.NomVia = NomVia;
            inValue.Numero = Numero;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).ObtenerNumereroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPLOC(AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest request) {
            return base.Channel.Consulta_DNPLOC(request);
        }
        
        public System.Xml.XmlNode Consulta_DNPLOC(string Provincia, string Municipio, string Sigla, string Calle, string Numero, string Bloque, string Escalera, string Planta, string Puerta) {
            AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.Sigla = Sigla;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Bloque = Bloque;
            inValue.Escalera = Escalera;
            inValue.Planta = Planta;
            inValue.Puerta = Puerta;
            AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPLOC(inValue);
            return retVal.Consulta_DNP;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPLOCAsync(AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest request) {
            return base.Channel.Consulta_DNPLOCAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPLOCResponse> Consulta_DNPLOCAsync(string Provincia, string Municipio, string Sigla, string Calle, string Numero, string Bloque, string Escalera, string Planta, string Puerta) {
            AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPLOCRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.Sigla = Sigla;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Bloque = Bloque;
            inValue.Escalera = Escalera;
            inValue.Planta = Planta;
            inValue.Puerta = Puerta;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPLOCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AzureMVC.ServicioCatastro.Consulta_DNPPPResponse AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPPP(AzureMVC.ServicioCatastro.Consulta_DNPPPRequest request) {
            return base.Channel.Consulta_DNPPP(request);
        }
        
        public System.Xml.XmlNode Consulta_DNPPP(string Provincia, string Municipio, string Poligono, string Parcela) {
            AzureMVC.ServicioCatastro.Consulta_DNPPPRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPPPRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.Poligono = Poligono;
            inValue.Parcela = Parcela;
            AzureMVC.ServicioCatastro.Consulta_DNPPPResponse retVal = ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPPP(inValue);
            return retVal.Consulta_DNPPP;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPPPResponse> AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap.Consulta_DNPPPAsync(AzureMVC.ServicioCatastro.Consulta_DNPPPRequest request) {
            return base.Channel.Consulta_DNPPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AzureMVC.ServicioCatastro.Consulta_DNPPPResponse> Consulta_DNPPPAsync(string Provincia, string Municipio, string Poligono, string Parcela) {
            AzureMVC.ServicioCatastro.Consulta_DNPPPRequest inValue = new AzureMVC.ServicioCatastro.Consulta_DNPPPRequest();
            inValue.Provincia = Provincia;
            inValue.Municipio = Municipio;
            inValue.Poligono = Poligono;
            inValue.Parcela = Parcela;
            return ((AzureMVC.ServicioCatastro.CallejerodelasedeelectrónicadelcatastroSoap)(this)).Consulta_DNPPPAsync(inValue);
        }
    }
}
