//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicioEmpleados.ServiceEmpleados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/LogicaEmpleados.Models")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OficioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oficio {
            get {
                return this.OficioField;
            }
            set {
                if ((object.ReferenceEquals(this.OficioField, value) != true)) {
                    this.OficioField = value;
                    this.RaisePropertyChanged("Oficio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleados.IServiceEmpleados")]
    public interface IServiceEmpleados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleados/GetOficios", ReplyAction="http://tempuri.org/IServiceEmpleados/GetOficiosResponse")]
        string[] GetOficios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleados/GetOficios", ReplyAction="http://tempuri.org/IServiceEmpleados/GetOficiosResponse")]
        System.Threading.Tasks.Task<string[]> GetOficiosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleados/GetEmpleadosOficio", ReplyAction="http://tempuri.org/IServiceEmpleados/GetEmpleadosOficioResponse")]
        ClienteServicioEmpleados.ServiceEmpleados.Empleado[] GetEmpleadosOficio(string oficio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleados/GetEmpleadosOficio", ReplyAction="http://tempuri.org/IServiceEmpleados/GetEmpleadosOficioResponse")]
        System.Threading.Tasks.Task<ClienteServicioEmpleados.ServiceEmpleados.Empleado[]> GetEmpleadosOficioAsync(string oficio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpleadosChannel : ClienteServicioEmpleados.ServiceEmpleados.IServiceEmpleados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpleadosClient : System.ServiceModel.ClientBase<ClienteServicioEmpleados.ServiceEmpleados.IServiceEmpleados>, ClienteServicioEmpleados.ServiceEmpleados.IServiceEmpleados {
        
        public ServiceEmpleadosClient() {
        }
        
        public ServiceEmpleadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpleadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetOficios() {
            return base.Channel.GetOficios();
        }
        
        public System.Threading.Tasks.Task<string[]> GetOficiosAsync() {
            return base.Channel.GetOficiosAsync();
        }
        
        public ClienteServicioEmpleados.ServiceEmpleados.Empleado[] GetEmpleadosOficio(string oficio) {
            return base.Channel.GetEmpleadosOficio(oficio);
        }
        
        public System.Threading.Tasks.Task<ClienteServicioEmpleados.ServiceEmpleados.Empleado[]> GetEmpleadosOficioAsync(string oficio) {
            return base.Channel.GetEmpleadosOficioAsync(oficio);
        }
    }
}
