//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lambda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFERMO
    {
        public string INSCRIPCION { get; set; }
        public string APELLIDO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<System.DateTime> FECHA_NAC { get; set; }
        public string S { get; set; }
        public string NSS { get; set; }
    }
}
