//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICPANTS
    {
        public int ID_PARTICPANT { get; set; }
        public int ID_PARTY { get; set; }
        public int ID_PLAYER { get; set; }
        public bool LEADER_PARTICIPANT { get; set; }
    
        public virtual PARTIES PARTIES { get; set; }
        public virtual PLAYERS PLAYERS { get; set; }
    }
}
