//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICPANTS
    {
        public int ID_PARTICPANT { get; set; }
        public int ID_PARTY { get; set; }
        public int ID_PLAYER { get; set; }
        public bool LEADER_PARTICIPANT { get; set; }
    
        public virtual PARTIES PARTIES { get; set; }
        public virtual PLAYERS PLAYERS { get; set; }
    }
}
