//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBS()
        {
            this.PARTIES = new HashSet<PARTIES>();
            this.TICKETS = new HashSet<TICKETS>();
        }
    
        public int ID_PUB { get; set; }
        public int ID_CLIENT { get; set; }
        public string NAME_PUB { get; set; }
        public string ADDRESS_PUB { get; set; }
        public string CP_PUB { get; set; }
        public string PHONE_PUB { get; set; }
        public string STATUS_PUB { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIES> PARTIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETS> TICKETS { get; set; }
    }
}
