//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TcapContext : DbContext
    {
        public TcapContext()
            : base("name=TcapContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TOKENS> TOKENS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<PARTICPANTS> PARTICPANTS { get; set; }
        public virtual DbSet<PARTIES> PARTIES { get; set; }
        public virtual DbSet<PLAYERS> PLAYERS { get; set; }
        public virtual DbSet<PUBS> PUBS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<STATUSES> STATUSES { get; set; }
        public virtual DbSet<TICKETS> TICKETS { get; set; }
    }
}
