#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TCAP")]
	public partial class TCAPContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TCAPContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TCAPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TCAPContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCAPContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCAPContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCAPContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[CONFIRM]")]
		public ISingleResult<CONFIRMResult> CONFIRM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="T", DbType="Text")] string t, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR", DbType="NVarChar(255)")] ref string eRROR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), t, eRROR);
			eRROR = ((string)(result.GetParameterValue(1)));
			return ((ISingleResult<CONFIRMResult>)(result.ReturnValue));
		}
	}
	
	public partial class CONFIRMResult
	{
		
		private int _ID_USER;
		
		public CONFIRMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
