<?xml version="1.0" encoding="utf-8"?><Database Name="TCAP" Class="TCAPContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST;Initial Catalog=TCAP;Persist Security Info=True;User ID=SA" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TCAPConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.[CONFIRM]" Method="CONFIRM">
    <Parameter Name="T" Parameter="t" Type="System.String" DbType="Text" />
    <Parameter Name="ERROR" Parameter="eRROR" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <ElementType Name="CONFIRMResult">
      <Column Name="ID_USER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>