//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int ID_TICKET { get; set; }
        public int ID_PLAYER { get; set; }
        public int ID_PUB { get; set; }
        public System.DateTime CREATED_TICKET { get; set; }
        public decimal QUANTITY_TICKET { get; set; }
    
        public virtual PLAYERS PLAYERS { get; set; }
        public virtual PUBS PUBS { get; set; }
    }
}
