//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int ID_TICKET { get; set; }
        public int ID_PLAYER { get; set; }
        public int ID_PUB { get; set; }
        public System.DateTime CREATED_TICKET { get; set; }
        public decimal QUANTITY_TICKET { get; set; }
    
        public virtual PLAYERS PLAYERS { get; set; }
        public virtual PUBS PUBS { get; set; }
    }
}
