//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKENS
    {
        public int ID_TOKEN { get; set; }
        public int ID_USER { get; set; }
        public string VALUE_TOKEN { get; set; }
        public System.DateTime START_TOKEN { get; set; }
        public System.DateTime END_TOKEN { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
