//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.TOKENS = new HashSet<TOKENS>();
            this.CLIENTS = new HashSet<CLIENTS>();
            this.PLAYERS = new HashSet<PLAYERS>();
        }
    
        public int ID_USER { get; set; }
        public int ID_ROL { get; set; }
        public string NAME_USER { get; set; }
        public string SURNAME_USER { get; set; }
        public string EMAIL_USER { get; set; }
        public string PASSWORD_USER { get; set; }
        public string IMAGE_USER { get; set; }
        public System.DateTime CREATED_USER { get; set; }
        public System.DateTime UPDATED_USER { get; set; }
        public int STATUS_USER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOKENS> TOKENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYERS> PLAYERS { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual STATUSES STATUSES { get; set; }
    }
}
